apiVersion: v1
kind: Service
metadata:
  name: springboot-example
  namespace: myapp
  labels:
    app.kubernetes.io/name: springboot-example
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: springboot-example
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080